In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./data/cn/combined_output.csv", index_col=False)

In [3]:
data

,Price,Datetime,Open,High,Low,Close,Adj Close,Volume,ticker
0,Ticker,NaN,002555.SZ,002555.SZ,002555.SZ,002555.SZ,002555.SZ,002555.SZ,NaN
1,0,2024-08-26 01:30:00+00:00,12.350000381469727,12.5,12.170000076293945,12.390000343322754,12.390000343322754,12670540,002555.SZ
2,1,2024-08-26 02:30:00+00:00,12.390000343322754,12.470000267028809,12.359999656677246,12.40999984741211,12.40999984741211,2899100,002555.SZ
3,2,2024-08-26 03:30:00+00:00,12.40999984741211,12.40999984741211,12.40999984741211,12.40999984741211,12.40999984741211,0,002555.SZ
4,3,2024-08-26 04:30:00+00:00,12.40999984741211,12.40999984741211,12.350000381469727,12.380000114440918,12.380000114440918,17058440,002555.SZ
...,...,...,...,...,...,...,...,...,...
119517,208,2024-10-22 05:30:00+00:00,43.650001525878906,44.25,43.54999923706055,43.880001068115234,43.880001068115234,12170470,002714.SZ
119518,209,2024-10-22 06:30:00+00:00,43.88999938964844,43.970001220703125,43.709999084472656,43.970001220703125,43.970001220703125,0,002714.SZ
119519,210,2024-10-23 01:30:00+00:00,44.31999969482422,44.31999969482422,43.40999984741211,43.5,43.5,0,002714.SZ
119520,211,2024-10-23 02:30:00+00:00,43.5,43.70000076293945,43.33000183105469,43.58000183105469,43.58000183105469,7156801,002714.SZ
119521,212,2024-10-23 03:30:00+00:00,43.58000183105469,43.58000183105469,43.58000183105469,43.58000183105469,43.58000183105469,0,002714.SZ

In [4]:
data.info

<bound method DataFrame.info of          Price                   Datetime                Open  \
0       Ticker                        NaN           002555.SZ
1            0  2024-08-26 01:30:00+00:00  12.350000381469727
2            1  2024-08-26 02:30:00+00:00  12.390000343322754
3            2  2024-08-26 03:30:00+00:00   12.40999984741211
4            3  2024-08-26 04:30:00+00:00   12.40999984741211
...        ...                        ...                 ...
119517     208  2024-10-22 05:30:00+00:00  43.650001525878906
119518     209  2024-10-22 06:30:00+00:00   43.88999938964844
119519     210  2024-10-23 01:30:00+00:00   44.31999969482422
119520     211  2024-10-23 02:30:00+00:00                43.5
119521     212  2024-10-23 03:30:00+00:00   43.58000183105469

                      High                 Low               Close  \
0                002555.SZ           002555.SZ           002555.SZ
1                     12.5  12.170000076293945  12.390000343322754
2       12.470000267028809  12.359999656677246   12.40999984741211
3        12.40999984741211   12.40999984741211   12.40999984741211
4        12.40999984741211  12.350000381469727  12.380000114440918
...                    ...                 ...                 ...
119517               44.25   43.54999923706055  43.880001068115234
119518  43.970001220703125  43.709999084472656  43.970001220703125
119519   44.31999969482422   43.40999984741211                43.5
119520   43.70000076293945   43.33000183105469   43.58000183105469
119521   43.58000183105469   43.58000183105469   43.58000183105469

                 Adj Close     Volume     ticker
0                002555.SZ  002555.SZ        NaN
1       12.390000343322754   12670540  002555.SZ
2        12.40999984741211    2899100  002555.SZ
3        12.40999984741211          0  002555.SZ
4       12.380000114440918   17058440  002555.SZ
...                    ...        ...        ...
119517  43.880001068115234   12170470  002714.SZ
119518  43.970001220703125          0  002714.SZ
119519                43.5          0  002714.SZ
119520   43.58000183105469    7156801  002714.SZ
119521   43.58000183105469          0  002714.SZ

[119522 rows x 9 columns]>

In [9]:
import yfinance as yf
import pandas as pd
import pandas_ta as ta

In [10]:
df = pd.DataFrame()

df = yf.download("^GSPC", interval="1h", period="max")

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['^GSPC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1h 2022-10-28 02:22:37-04:00 -> 2024-10-27 02:22:37-04:00) (Yahoo error = "1h data not available for startTime=1666938157 and endTime=1730010157. The requested range must be within the last 730 days.")')

In [15]:
df.info

help(df.ta)

Help on AnalysisIndicators in module pandas_ta.core object:

class AnalysisIndicators(BasePandasObject)
 |  AnalysisIndicators(pandas_obj)
 |
 |  This Pandas Extension is named 'ta' for Technical Analysis. In other words,
 |  it is a Numerical Time Series Feature Generator where the Time Series data
 |  is biased towards Financial Market data; typical data includes columns
 |  named :"open", "high", "low", "close", "volume".
 |
 |  This TA Library hopefully allows you to apply familiar and unique Technical
 |  Analysis Indicators easily with the DataFrame Extension named 'ta'. Even
 |  though 'ta' is a Pandas DataFrame Extension, you can still call Technical
 |  Analysis indicators individually if you are more comfortable with that
 |  approach or it allows you to easily and automatically apply the indicators
 |  with the strategy method. See: help(ta.strategy).
 |
 |  By default, the 'ta' extension uses lower case column names: open, high,
 |  low, close, and volume. You can override the defaults by providing the it's
 |  replacement name when calling the indicator. For example, to call the
 |  indicator hl2().
 |
 |  With 'default' columns: open, high, low, close, and volume.
 |  >>> df.ta.hl2()
 |  >>> df.ta(kind="hl2")
 |
 |  With DataFrame columns: Open, High, Low, Close, and Volume.
 |  >>> df.ta.hl2(high="High", low="Low")
 |  >>> df.ta(kind="hl2", high="High", low="Low")
 |
 |  If you do not want to use a DataFrame Extension, just call it normally.
 |  >>> sma10 = ta.sma(df["Close"]) # Default length=10
 |  >>> sma50 = ta.sma(df["Close"], length=50)
 |  >>> ichimoku, span = ta.ichimoku(df["High"], df["Low"], df["Close"])
 |
 |  Args:
 |      kind (str, optional): Default: None. Kind is the 'name' of the indicator.
 |          It converts kind to lowercase before calling.
 |      timed (bool, optional): Default: False. Curious about the execution
 |          speed?
 |      kwargs: Extension specific modifiers.
 |          append (bool, optional): Default: False. When True, it appends the
 |          resultant column(s) to the DataFrame.
 |
 |  Returns:
 |      Most Indicators will return a Pandas Series. Others like MACD, BBANDS,
 |      KC, et al will return a Pandas DataFrame. Ichimoku on the other hand
 |      will return two DataFrames, the Ichimoku DataFrame for the known period
 |      and a Span DataFrame for the future of the Span values.
 |
 |  Let's get started!
 |
 |  1. Loading the 'ta' module:
 |  >>> import pandas as pd
 |  >>> import ta as ta
 |
 |  2. Load some data:
 |  >>> df = pd.read_csv("AAPL.csv", index_col="date", parse_dates=True)
 |
 |  3. Help!
 |  3a. General Help:
 |  >>> help(df.ta)
 |  >>> df.ta()
 |  3b. Indicator Help:
 |  >>> help(ta.apo)
 |  3c. Indicator Extension Help:
 |  >>> help(df.ta.apo)
 |
 |  4. Ways of calling an indicator.
 |  4a. Standard: Calling just the APO indicator without "ta" DataFrame extension.
 |  >>> ta.apo(df["close"])
 |  4b. DataFrame Extension: Calling just the APO indicator with "ta" DataFrame extension.
 |  >>> df.ta.apo()
 |  4c. DataFrame Extension (kind): Calling APO using 'kind'
 |  >>> df.ta(kind="apo")
 |  4d. Strategy:
 |  >>> df.ta.strategy("All") # Default
 |  >>> df.ta.strategy(ta.Strategy("My Strat", ta=[{"kind": "apo"}])) # Custom
 |
 |  5. Working with kwargs
 |  5a. Append the result to the working df.
 |  >>> df.ta.apo(append=True)
 |  5b. Timing an indicator.
 |  >>> apo = df.ta(kind="apo", timed=True)
 |  >>> print(apo.timed)
 |
 |  Method resolution order:
 |      AnalysisIndicators
 |      BasePandasObject
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __call__(self, kind: str = None, timed: bool = False, version: bool = False, **kwargs)
 |      Call self as a function.
 |
 |  __init__(self, pandas_obj)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  aberration(self, length=None, atr_length=None, offset=None, **kwargs)
 |      # Volatility
 |
 |  above(self, asint=True, offset=None, **kwargs)
 |      # Utility
 |
 |  above_value(self, value=None, asint=True, offset=None, **kwargs)
 |
 |  accbands(self, length=None, c=None, mamode=None, offset=None, **kwargs)
 |
 |  ad(self, open_=None, signed=True, offset=None, **kwargs)
 |      # Volume
 |
 |  adosc(self, open_=None, fast=None, slow=None, signed=True, offset=None, **kwargs)
 |
 |  adx(self, length=None, lensig=None, mamode=None, scalar=None, drift=None, offset=None, **kwargs)
 |      # Trend
 |
 |  alma(self, length=None, sigma=None, distribution_offset=None, offset=None, **kwargs)
 |      # Overlap
 |
 |  amat(self, fast=None, slow=None, mamode=None, lookback=None, offset=None, **kwargs)
 |
 |  ao(self, fast=None, slow=None, offset=None, **kwargs)
 |      # Momentum
 |
 |  aobv(self, fast=None, slow=None, mamode=None, max_lookback=None, min_lookback=None, offset=None, **kwargs)
 |
 |  apo(self, fast=None, slow=None, mamode=None, offset=None, **kwargs)
 |
 |  aroon(self, length=None, scalar=None, offset=None, **kwargs)
 |
 |  atr(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  bbands(self, length=None, std=None, mamode=None, offset=None, **kwargs)
 |
 |  below(self, asint=True, offset=None, **kwargs)
 |
 |  below_value(self, value=None, asint=True, offset=None, **kwargs)
 |
 |  bias(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  bop(self, percentage=False, offset=None, **kwargs)
 |
 |  brar(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  cci(self, length=None, c=None, offset=None, **kwargs)
 |
 |  cdl_pattern(self, name='all', offset=None, **kwargs)
 |      # Public DataFrame Methods: Indicators and Utilities
 |      # Candles
 |
 |  cdl_z(self, full=None, offset=None, **kwargs)
 |
 |  cfo(self, length=None, offset=None, **kwargs)
 |
 |  cg(self, length=None, offset=None, **kwargs)
 |
 |  chop(self, length=None, atr_length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  cksp(self, p=None, x=None, q=None, mamode=None, offset=None, **kwargs)
 |
 |  cmf(self, open_=None, length=None, offset=None, **kwargs)
 |
 |  cmo(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  constants(self, append: bool, values: list)
 |      Constants
 |
 |      Add or remove constants to the DataFrame easily with Numpy's arrays or
 |      lists. Useful when you need easily accessible horizontal lines for
 |      charting.
 |
 |      Add constant '1' to the DataFrame
 |      >>> df.ta.constants(True, [1])
 |      Remove constant '1' to the DataFrame
 |      >>> df.ta.constants(False, [1])
 |
 |      Adding constants for charting
 |      >>> import numpy as np
 |      >>> chart_lines = np.append(np.arange(-4, 5, 1), np.arange(-100, 110, 10))
 |      >>> df.ta.constants(True, chart_lines)
 |      Removing some constants from the DataFrame
 |      >>> df.ta.constants(False, np.array([-60, -40, 40, 60]))
 |
 |      Args:
 |          append (bool): If True, appends a Numpy range of constants to the
 |              working DataFrame.  If False, it removes the constant range from
 |              the working DataFrame. Default: None.
 |
 |      Returns:
 |          Returns the appended constants
 |          Returns nothing to the user.  Either adds or removes constant ranges
 |          from the working DataFrame.
 |
 |  coppock(self, length=None, fast=None, slow=None, offset=None, **kwargs)
 |
 |  cross(self, above=True, asint=True, offset=None, **kwargs)
 |
 |  cross_value(self, value=None, above=True, asint=True, offset=None, **kwargs)
 |
 |  cti(self, length=None, offset=None, **kwargs)
 |
 |  decay(self, length=None, mode=None, offset=None, **kwargs)
 |
 |  decreasing(self, length=None, strict=None, asint=None, offset=None, **kwargs)
 |
 |  dema(self, length=None, offset=None, **kwargs)
 |
 |  dm(self, drift=None, offset=None, mamode=None, **kwargs)
 |
 |  donchian(self, lower_length=None, upper_length=None, offset=None, **kwargs)
 |
 |  dpo(self, length=None, centered=True, offset=None, **kwargs)
 |
 |  ebsw(self, close=None, length=None, bars=None, offset=None, **kwargs)
 |      # Cycles
 |
 |  efi(self, length=None, mamode=None, offset=None, drift=None, **kwargs)
 |
 |  ema(self, length=None, offset=None, **kwargs)
 |
 |  entropy(self, length=None, base=None, offset=None, **kwargs)
 |      # Statistics
 |
 |  eom(self, length=None, divisor=None, offset=None, drift=None, **kwargs)
 |
 |  er(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  eri(self, length=None, offset=None, **kwargs)
 |
 |  fisher(self, length=None, signal=None, offset=None, **kwargs)
 |
 |  fwma(self, length=None, offset=None, **kwargs)
 |
 |  ha(self, offset=None, **kwargs)
 |
 |  hilo(self, high_length=None, low_length=None, mamode=None, offset=None, **kwargs)
 |
 |  hl2(self, offset=None, **kwargs)
 |
 |  hlc3(self, offset=None, **kwargs)
 |
 |  hma(self, length=None, offset=None, **kwargs)
 |
 |  hwc(self, na=None, nb=None, nc=None, nd=None, scalar=None, offset=None, **kwargs)
 |
 |  hwma(self, na=None, nb=None, nc=None, offset=None, **kwargs)
 |
 |  ichimoku(self, tenkan=None, kijun=None, senkou=None, include_chikou=True, offset=None, **kwargs)
 |
 |  increasing(self, length=None, strict=None, asint=None, offset=None, **kwargs)
 |
 |  indicators(self, **kwargs)
 |      List of Indicators
 |
 |      kwargs:
 |          as_list (bool, optional): When True, it returns a list of the
 |              indicators. Default: False.
 |          exclude (list, optional): The passed in list will be excluded
 |              from the indicators list. Default: None.
 |
 |      Returns:
 |          Prints the list of indicators. If as_list=True, then a list.
 |
 |  inertia(self, length=None, rvi_length=None, scalar=None, refined=None, thirds=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  jma(self, length=None, phase=None, offset=None, **kwargs)
 |
 |  kama(self, length=None, fast=None, slow=None, offset=None, **kwargs)
 |
 |  kc(self, length=None, scalar=None, mamode=None, offset=None, **kwargs)
 |
 |  kdj(self, length=None, signal=None, offset=None, **kwargs)
 |
 |  kst(self, roc1=None, roc2=None, roc3=None, roc4=None, sma1=None, sma2=None, sma3=None, sma4=None, signal=None, offset=None, **kwargs)
 |
 |  kurtosis(self, length=None, offset=None, **kwargs)
 |
 |  kvo(self, fast=None, slow=None, length_sig=None, mamode=None, offset=None, drift=None, **kwargs)
 |
 |  linreg(self, length=None, offset=None, adjust=None, **kwargs)
 |
 |  log_return(self, length=None, cumulative=False, percent=False, offset=None, **kwargs)
 |      # Performance
 |
 |  long_run(self, fast=None, slow=None, length=None, offset=None, **kwargs)
 |
 |  macd(self, fast=None, slow=None, signal=None, offset=None, **kwargs)
 |
 |  mad(self, length=None, offset=None, **kwargs)
 |
 |  massi(self, fast=None, slow=None, offset=None, **kwargs)
 |
 |  mcgd(self, length=None, offset=None, **kwargs)
 |
 |  median(self, length=None, offset=None, **kwargs)
 |
 |  mfi(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  midpoint(self, length=None, offset=None, **kwargs)
 |
 |  midprice(self, length=None, offset=None, **kwargs)
 |
 |  mom(self, length=None, offset=None, **kwargs)
 |
 |  natr(self, length=None, mamode=None, scalar=None, offset=None, **kwargs)
 |
 |  nvi(self, length=None, initial=None, signed=True, offset=None, **kwargs)
 |
 |  obv(self, offset=None, **kwargs)
 |
 |  ohlc4(self, offset=None, **kwargs)
 |
 |  pdist(self, drift=None, offset=None, **kwargs)
 |
 |  percent_return(self, length=None, cumulative=False, percent=False, offset=None, **kwargs)
 |
 |  pgo(self, length=None, offset=None, **kwargs)
 |
 |  ppo(self, fast=None, slow=None, scalar=None, mamode=None, offset=None, **kwargs)
 |
 |  psar(self, af0=None, af=None, max_af=None, offset=None, **kwargs)
 |
 |  psl(self, open_=None, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  pvi(self, length=None, initial=None, signed=True, offset=None, **kwargs)
 |
 |  pvo(self, fast=None, slow=None, signal=None, scalar=None, offset=None, **kwargs)
 |
 |  pvol(self, volume=None, offset=None, **kwargs)
 |
 |  pvr(self, **kwargs)
 |
 |  pvt(self, offset=None, **kwargs)
 |
 |  pwma(self, length=None, offset=None, **kwargs)
 |
 |  qqe(self, length=None, smooth=None, factor=None, mamode=None, offset=None, **kwargs)
 |
 |  qstick(self, length=None, offset=None, **kwargs)
 |
 |  quantile(self, length=None, q=None, offset=None, **kwargs)
 |
 |  rma(self, length=None, offset=None, **kwargs)
 |
 |  roc(self, length=None, offset=None, **kwargs)
 |
 |  rsi(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  rsx(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  rvgi(self, length=None, swma_length=None, offset=None, **kwargs)
 |
 |  rvi(self, length=None, scalar=None, refined=None, thirds=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  short_run(self, fast=None, slow=None, length=None, offset=None, **kwargs)
 |
 |  sinwma(self, length=None, offset=None, **kwargs)
 |
 |  skew(self, length=None, offset=None, **kwargs)
 |
 |  slope(self, length=None, offset=None, **kwargs)
 |
 |  sma(self, length=None, offset=None, **kwargs)
 |
 |  smi(self, fast=None, slow=None, signal=None, scalar=None, offset=None, **kwargs)
 |
 |  squeeze(self, bb_length=None, bb_std=None, kc_length=None, kc_scalar=None, mom_length=None, mom_smooth=None, use_tr=None, mamode=None, offset=None, **kwargs)
 |
 |  squeeze_pro(self, bb_length=None, bb_std=None, kc_length=None, kc_scalar_wide=None, kc_scalar_normal=None, kc_scalar_narrow=None, mom_length=None, mom_smooth=None, use_tr=None, mamode=None, offset=None, **kwargs)
 |
 |  ssf(self, length=None, poles=None, offset=None, **kwargs)
 |
 |  stc(self, ma1=None, ma2=None, osc=None, tclength=None, fast=None, slow=None, factor=None, offset=None, **kwargs)
 |
 |  stdev(self, length=None, offset=None, **kwargs)
 |
 |  stoch(self, fast_k=None, slow_k=None, slow_d=None, mamode=None, offset=None, **kwargs)
 |
 |  stochrsi(self, length=None, rsi_length=None, k=None, d=None, mamode=None, offset=None, **kwargs)
 |
 |  strategy(self, *args, **kwargs)
 |      Strategy Method
 |
 |      An experimental method that by default runs all applicable indicators.
 |      Future implementations will allow more specific indicator generation
 |      with possibly as json, yaml config file or an sqlite3 table.
 |
 |
 |      Kwargs:
 |          chunksize (bool): Adjust the chunksize for the Multiprocessing Pool.
 |              Default: Number of cores of the OS
 |          exclude (list): List of indicator names to exclude. Some are
 |              excluded by default for various reasons; they require additional
 |              sources, performance (td_seq), not a ohlcv chart (vp) etc.
 |          name (str): Select all indicators or indicators by
 |              Category such as: "candles", "cycles", "momentum", "overlap",
 |              "performance", "statistics", "trend", "volatility", "volume", or
 |              "all". Default: "all"
 |          ordered (bool): Whether to run "all" in order. Default: True
 |          timed (bool): Show the process time of the strategy().
 |              Default: False
 |          verbose (bool): Provide some additional insight on the progress of
 |              the strategy() execution. Default: False
 |
 |  supertrend(self, period=None, multiplier=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  swma(self, length=None, offset=None, **kwargs)
 |
 |  t3(self, length=None, a=None, offset=None, **kwargs)
 |
 |  td_seq(self, asint=None, offset=None, show_all=None, **kwargs)
 |
 |  tema(self, length=None, offset=None, **kwargs)
 |
 |  thermo(self, long=None, short=None, length=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  ticker(self, ticker: str, **kwargs)
 |      ticker
 |
 |      This method downloads Historical Data if the package yfinance is installed.
 |      Additionally it can run a ta.Strategy; Builtin or Custom. It returns a
 |      DataFrame if there the DataFrame is not empty, otherwise it exits. For
 |      additional yfinance arguments, use help(ta.yf).
 |
 |      Historical Data
 |      >>> df = df.ta.ticker("aapl")
 |      More specifically
 |      >>> df = df.ta.ticker("aapl", period="max", interval="1d", kind=None)
 |
 |      Changing the period of Historical Data
 |      Period is used instead of start/end
 |      >>> df = df.ta.ticker("aapl", period="1y")
 |
 |      Changing the period and interval of Historical Data
 |      Retrieves the past year in weeks
 |      >>> df = df.ta.ticker("aapl", period="1y", interval="1wk")
 |      Retrieves the past month in hours
 |      >>> df = df.ta.ticker("aapl", period="1mo", interval="1h")
 |
 |      Show everything
 |      >>> df = df.ta.ticker("aapl", kind="all")
 |
 |      Args:
 |          ticker (str): Any string for a ticker you would use with yfinance.
 |              Default: "SPY"
 |      Kwargs:
 |          kind (str): Options see above. Default: "history"
 |          ds (str): Data Source to use. Default: "yahoo"
 |          strategy (str | ta.Strategy): Which strategy to apply after
 |              downloading chart history. Default: None
 |
 |          See help(ta.yf) for additional kwargs
 |
 |      Returns:
 |          Exits if the DataFrame is empty or None
 |          Otherwise it returns a DataFrame
 |
 |  tos_stdevall(self, length=None, stds=None, offset=None, **kwargs)
 |
 |  trima(self, length=None, offset=None, **kwargs)
 |
 |  trix(self, length=None, signal=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  true_range(self, drift=None, offset=None, **kwargs)
 |
 |  tsi(self, fast=None, slow=None, drift=None, mamode=None, offset=None, **kwargs)
 |
 |  tsignals(self, trend=None, asbool=None, trend_reset=None, trend_offset=None, offset=None, **kwargs)
 |
 |  ttm_trend(self, length=None, offset=None, **kwargs)
 |
 |  ui(self, length=None, scalar=None, offset=None, **kwargs)
 |
 |  uo(self, fast=None, medium=None, slow=None, fast_w=None, medium_w=None, slow_w=None, drift=None, offset=None, **kwargs)
 |
 |  variance(self, length=None, offset=None, **kwargs)
 |
 |  vhf(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  vidya(self, length=None, offset=None, **kwargs)
 |
 |  vortex(self, drift=None, offset=None, **kwargs)
 |
 |  vp(self, width=None, percent=None, **kwargs)
 |
 |  vwap(self, anchor=None, offset=None, **kwargs)
 |
 |  vwma(self, volume=None, length=None, offset=None, **kwargs)
 |
 |  wcp(self, offset=None, **kwargs)
 |
 |  willr(self, length=None, percentage=True, offset=None, **kwargs)
 |
 |  wma(self, length=None, offset=None, **kwargs)
 |
 |  xsignals(self, signal=None, xa=None, xb=None, above=None, long=None, asbool=None, trend_reset=None, trend_offset=None, offset=None, **kwargs)
 |
 |  zlma(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  zscore(self, length=None, std=None, offset=None, **kwargs)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  categories
 |      Returns the categories.
 |
 |  datetime_ordered
 |      Returns True if the index is a datetime and ordered.
 |
 |  last_run
 |      Returns the time when the DataFrame was last run.
 |
 |  reverse
 |      Reverses the DataFrame. Simply: df.iloc[::-1]
 |
 |  to_utc
 |      Sets the DataFrame index to UTC format
 |
 |  version
 |      Returns the version.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  adjusted
 |      property: df.ta.adjusted
 |
 |  cores
 |      Returns the categories.
 |
 |  exchange
 |      Returns the current Exchange. Default: "NYSE".
 |
 |  time_range
 |      Returns the time ranges of the DataFrame as a float. Default is in "years". help(ta.toal_time)
 |
 |  ----------------------------------------------------------------------

In [16]:
# List of all indicators
df.ta.indicators()

Pandas TA - Technical Analysis Indicators - v0.3.14b0
Total Indicators & Utilities: 205
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, alma, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_pattern, cdl_z, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, cti, decay, decreasing, dema, dm, donchian, dpo, ebsw, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, hwc, hwma, ichimoku, increasing, inertia, jma, kama, kc, kdj, kst, kurtosis, kvo, linreg, log_return, long_run, macd, mad, massi, mcgd, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvr, pvt, pwma, qqe, qstick, quantile, rma, roc, rsi, rsx, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, squeeze_pro, ssf, stc, stdev, stoch, stochrsi, supertrend, swma, t3, td_seq, tema, thermo, tos_stdevall, trima, trix, true_range, tsi, tsignals, ttm_trend, ui, uo, variance, vhf, vidya, vortex, vp, vwap, vwma, wcp, willr, wma, xsignals, zlma, zscore

Candle Patterns:
    2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods

In [17]:
# Help about an indicator such as bbands
help(ta.bbands)

Help on function bbands in module pandas_ta.volatility.bbands:

bbands(close, length=None, std=None, ddof=0, mamode=None, talib=None, offset=None, **kwargs)
    Bollinger Bands (BBANDS)

    A popular volatility indicator by John Bollinger.

    Sources:
        https://www.tradingview.com/wiki/Bollinger_Bands_(BB)

    Calculation:
        Default Inputs:
            length=5, std=2, mamode="sma", ddof=0
        EMA = Exponential Moving Average
        SMA = Simple Moving Average
        STDEV = Standard Deviation
        stdev = STDEV(close, length, ddof)
        if "ema":
            MID = EMA(close, length)
        else:
            MID = SMA(close, length)

        LOWER = MID - std * stdev
        UPPER = MID + std * stdev

        BANDWIDTH = 100 * (UPPER - LOWER) / MID
        PERCENT = (close - LOWER) / (UPPER - LOWER)

    Args:
        close (pd.Series): Series of 'close's
        length (int): The short period. Default: 5
        std (int): The long period. Default: 2
        ddof (int): Degrees of Freedom to use. Default: 0
        mamode (str): See ```help(ta.ma)```. Default: 'sma'
        talib (bool): If TA Lib is installed and talib is True, Returns the TA Lib
            version. Default: True
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.DataFrame: lower, mid, upper, bandwidth, and percent columns.

In [14]:
# Replace "datetime" with the appropriate column from your DataFrame
df.set_index(pd.DatetimeIndex(df["datetime"]), inplace=True)

KeyError: 'datetime'

In [24]:
spy_data.index.names

FrozenList(['Datetime'])

In [25]:
print(spy_data.columns)

MultiIndex([('Adj Close', '^GSPC'),
            (    'Close', '^GSPC'),
            (     'High', '^GSPC'),
            (      'Low', '^GSPC'),
            (     'Open', '^GSPC'),
            (   'Volume', '^GSPC')],
           names=['Price', 'Ticker'])

In [29]:
spy_data = spy_data.reset_index()  # Reset any existing index if needed
spy_data = spy_data.set_index("Datetime")  # Set 'Datetime' as the index

In [34]:
# Drop the 'Ticker' level from the columns
# spy_data.columns = spy_data.columns.droplevel('Ticker')
# spy_data.columns = spy_data.columns.name('Price')
spy_data.columns.name = None

In [35]:
print(spy_data.columns)

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [36]:
# If needed, reset the index (to bring 'Datetime' back as a column)
spy_data = spy_data.reset_index()

In [37]:
spy_data

,Datetime,Adj Close,Close,High,Low,Open,Volume
0,2022-10-25 15:30:00+00:00,3847.419922,3847.419922,3852.419922,3841.780029,3843.409912,0
1,2022-10-25 16:30:00+00:00,3840.100098,3840.100098,3848.989990,3834.189941,3847.439941,242473000
2,2022-10-25 17:30:00+00:00,3850.520020,3850.520020,3850.620117,3835.979980,3840.100098,237221000
3,2022-10-25 18:30:00+00:00,3858.270020,3858.270020,3858.489990,3845.780029,3850.540039,281067000
4,2022-10-25 19:30:00+00:00,3860.199951,3860.199951,3862.850098,3855.800049,3858.310059,412135000
...,...,...,...,...,...,...,...
3494,2024-10-23 18:30:00+00:00,5790.850098,5790.850098,5793.089844,5772.189941,5773.169922,243606000
3495,2024-10-23 19:30:00+00:00,5797.589844,5797.589844,5799.080078,5788.879883,5790.870117,344890000
3496,2024-10-24 13:30:00+00:00,5807.040039,5807.040039,5817.799805,5803.910156,5817.799805,421242054
3497,2024-10-24 14:30:00+00:00,5804.479980,5804.479980,5815.950195,5801.000000,5807.069824,251838175
3498,2024-10-24 15:30:00+00:00,5790.109863,5790.109863,5805.330078,5787.970215,5804.569824,150716432

In [38]:
print(spy_data.columns)

Index(['Datetime', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')